#!/usr/bin/env python
"""
instant_nostalgia

Send a text message to a phone number. Run the script as described below,
providing a seven digit U.S. phone number (digits only), the carrier it's on,
and a quoted message.  Supported carrier names are: "at&t", "cricket",
"sprint", "t-mobile", "u.s. cellular", "verizon", and "virgin".

Usage:
    footprinter <phone_number> <carrier_name> <message>

Options:
    -h --help                   Show this screen.

"""
import sys

from docopt import docopt

from lib import send_message


def main(args):
    send_message(
        args['<phone_number>'], args['<carrier_name>'], args['<message>'])
    print "Message sent."


if __name__ == '__main__':
    try:
        main(docopt(__doc__))
    except Exception as ex:
        print "Error: {}".format(ex)
        sys.exit(1)
