#!/usr/bin/env python
"""
instant_nostalgia

Send yourself a text message one hour from now.  Run the script as described
below, providing a seven digit U.S. phone number (digits only) and a quoted
message.

Usage:
    footprinter <phone_number> <message>

Options:
    -h --help                   Show this screen.

"""
import sys

from docopt import docopt

from lib import send_message


def main(args):
    phone_number = _validate_phone_number(args['<phone_number>'])
    message = args['<message>']
    send_message(phone_number, message)


def _validate_phone_number(phone_number):
    error_message = ("Please provide your phone number as 7 digits only. (No "
                     "punctuation, letters or spaces)")
    if len(phone_number) != 7:
        raise ValueError(error_message)
    try:
        return int(phone_number)
    except ValueError:
        raise ValueError(error_message)


if __name__ == '__main__':
    try:
        main(docopt(__doc__))
    except Exception as ex:
        print "Error: {}".format(ex)
        sys.exit(1)
